//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBRMnerWeb
{
    public partial class SalesCRM
    {
        // Alerts
        protected global::System.Web.UI.WebControls.Panel     pnlError;
        protected global::System.Web.UI.WebControls.Label     lblError;
        protected global::System.Web.UI.WebControls.Panel     pnlSuccess;
        protected global::System.Web.UI.WebControls.Label     lblSuccess;

        // Hidden fields for customer detail persistence
        protected global::System.Web.UI.WebControls.HiddenField hfCustName;
        protected global::System.Web.UI.WebControls.HiddenField hfCustRMN;
        protected global::System.Web.UI.WebControls.HiddenField hfSolId;
        protected global::System.Web.UI.WebControls.HiddenField hfCustEmail;
        protected global::System.Web.UI.WebControls.HiddenField hfBranchName;

        // CTI read-only labels
        protected global::System.Web.UI.WebControls.Label lblUCID;
        protected global::System.Web.UI.WebControls.Label lblLanguage;
        protected global::System.Web.UI.WebControls.Label lblCTIAccountNo;
        protected global::System.Web.UI.WebControls.Label lblCustId;
        protected global::System.Web.UI.WebControls.Label lblCallerANI;
        protected global::System.Web.UI.WebControls.Label lblRMNFlag;
        protected global::System.Web.UI.WebControls.Label lblSkillSet;
        protected global::System.Web.UI.WebControls.Label lblExistingCustomer;
        protected global::System.Web.UI.WebControls.Label lblIVRLastNodes;

        // Customer search
        protected global::System.Web.UI.WebControls.TextBox  txtSearchTerm;
        protected global::System.Web.UI.WebControls.Button   btnSearch;
        protected global::System.Web.UI.WebControls.Panel    pnlCustomerInfo;
        protected global::System.Web.UI.WebControls.Label    lblCustName;
        protected global::System.Web.UI.WebControls.Label    lblCustRMN;
        protected global::System.Web.UI.WebControls.Label    lblSolId;
        protected global::System.Web.UI.WebControls.Label    lblCustEmail;
        protected global::System.Web.UI.WebControls.Label    lblBranchName;

        // Warm Transfer
        protected global::System.Web.UI.WebControls.Button btnWarmTransfer;

        // Data Capture form
        protected global::System.Web.UI.WebControls.DropDownList ddlProduct;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubProduct;
        protected global::System.Web.UI.WebControls.TextBox      txtDataCustName;
        protected global::System.Web.UI.WebControls.TextBox      txtDataEmail;
        protected global::System.Web.UI.WebControls.TextBox      txtAltContact;
        protected global::System.Web.UI.WebControls.DropDownList ddlDisposition;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDisposition;
        protected global::System.Web.UI.WebControls.TextBox      txtDemandedAmount;
        protected global::System.Web.UI.WebControls.TextBox      txtAppointmentDate;
        protected global::System.Web.UI.WebControls.TextBox      txtAppointmentTime;
        protected global::System.Web.UI.WebControls.DropDownList ddlBranchSMSDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlSelect;
        protected global::System.Web.UI.WebControls.TextBox      txtAddress;
        protected global::System.Web.UI.WebControls.TextBox      txtRemarks;
        protected global::System.Web.UI.WebControls.Button       btnSubmit;

        // History
        protected global::System.Web.UI.WebControls.LinkButton lnkSalesHistory;
        protected global::System.Web.UI.WebControls.LinkButton lnkInboundHistory;
        protected global::System.Web.UI.WebControls.LinkButton lnkCustHistory;

        // Actions
        protected global::System.Web.UI.WebControls.Button btnClickForOffers;
        protected global::System.Web.UI.WebControls.Button btnInternalTransfer;
    }
}
